backend:
  name: git-gateway
media_folder: static/assets
public_folder: assets
site_url: https://awakened.netlify.com/
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: comics
    identifier_field: number
    extension: json
    label: Comics
    label_singular: Comic
    folder: comics
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - label: Number
        name: number
        widget: number
        valueType: int
        min: 1
      - { label: Image, name: image, widget: file }
      - label: Date
        name: date
        widget: datetime
        format: "MM-DD-YYYY"
      - label: Body
        name: body
        widget: markdown
