backend:
  name: git-gateway
media_folder: data/images
# public_folder: images
site_url: https://awakened.netlify.com/
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: pages
    identifier_field: page_number
    extension: json
    label: Pages
    label_singular: Page
    folder: data/pages
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - label: Page Number
        name: page_number
        widget: number
        valueType: int
        min: 1
      - { label: Image, name: image, widget: file }
      - label: Date
        name: date
        widget: datetime
        format: "MM-DD-YYYY"
      - label: Body
        name: body
        required: false
        widget: markdown
  - name: chapters
    identifier_field: number
    extension: json
    label: Chapters
    label_singuler: Chapter
    folder: data/chapters
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - label: Chapter Number
        name: number
        widget: number
        valueType: int
        min: 1
      - label: Chapter Title
        name: title
        widget: string
      - label: First Page Number of Chapter
        name: page_number
        widget: number
        valueType: int
        min: 1
