backend:
  name: github
  repo: krnsk0/webcomic-site
media_folder: static/assets
public_folder: assets
site_url: https://awakened.netlify.com/
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: comic
    identifier_field: name
    extension: json
    label: Comic
    folder: comics
    create: true
    delete: true
    fields:
      - { name: number, label: Number }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, label: Image }
      - { name: body, label: Body, widget: markdown }
